services:
  - type: web
    name: eld-log-api
    plan: free
    runtime: python
    buildCommand: ./build.sh
    startCommand: python manage.py runserver
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.3
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: eld_log.settings
      - key: DEBUG
        value: false 