# Generated by Django 5.1.7 on 2025-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='shipping_number',
            field=models.CharField(blank=True, help_text='Pro or Shipping Number for driver logs', max_length=50, null=True),
        ),
    ]
